// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VizitLink3D.SuperAdmin.VeriTabani;

#nullable disable

namespace VizitLink3D.SuperAdmin.VeriTabani.Migrations
{
    [DbContext(typeof(SuperAdminDbContext))]
    [Migration("20260807142054_SuperAdminLisansTablosu")]
    partial class SuperAdminLisansTablosu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("VizitLink3D.Ortak.Modeller.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("AciklamaKisa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminTema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AktifModulKodlariJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AktifSablonId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Boylam")
                        .HasColumnType("REAL");

                    b.Property<string>("CalismaSaatleri")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DemoMu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Enlem")
                        .HasColumnType("REAL");

                    b.Property<string>("Eposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Facebook")
                        .HasColumnType("TEXT");

                    b.Property<string>("Favicon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KurulusYili")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogoMaxYukseklik")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxKullaniciSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedyaKlasoru")
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuDikeyPadding")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuYatayAralik")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaketTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pinterest")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sehir")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sektor")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteTema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TasarimRengi1")
                        .HasColumnType("TEXT");

                    b.Property<string>("TasarimRengi2")
                        .HasColumnType("TEXT");

                    b.Property<string>("TasarimRengi3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon2")
                        .HasColumnType("TEXT");

                    b.Property<string>("TiktokKanal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Twitter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ulke")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("TEXT");

                    b.Property<string>("YedekDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("YetkiliAdSoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeKanal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("VizitLink3D.Ortak.Modeller.FirmaModulAtama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtanmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModulId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("ModulId");

                    b.ToTable("FirmaModulAtamalari");
                });

            modelBuilder.Entity("VizitLink3D.Ortak.Modeller.Lisans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirincilDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DemoMu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("LisansAnahtari")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LisansTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonDogrulamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SureYil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SuresizMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YedekDomain")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "AktifMi");

                    b.ToTable("Lisanslar");
                });

            modelBuilder.Entity("VizitLink3D.Ortak.Modeller.Modul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SistemModuluMu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VarsayilanMi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Moduller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Blog",
                            Kategori = "Icerik",
                            Kod = "blog",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Galeri",
                            Kategori = "Icerik",
                            Kod = "galeri",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Iletisim Formu",
                            Kategori = "Iletisim",
                            Kod = "iletisim",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Canli Sohbet",
                            Kategori = "Iletisim",
                            Kod = "sohbet",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Medya Havuzu",
                            Kategori = "Medya",
                            Kod = "medya_havuzu",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 6,
                            Ad = "AI Asistan",
                            Kategori = "AI",
                            Kod = "ai_asistan",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 7,
                            Ad = "3D Goruntu",
                            Kategori = "Gorsel",
                            Kod = "3d_goruntu",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Urun Yonetimi",
                            Kategori = "E-Ticaret",
                            Kod = "urunler",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Haber Yonetimi",
                            Kategori = "Icerik",
                            Kod = "haberler",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Sayfa Yonetimi",
                            Kategori = "Icerik",
                            Kod = "sayfalar",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Menu Yonetimi",
                            Kategori = "Yonetim",
                            Kod = "menu_yonetimi",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 12,
                            Ad = "Tema Yonetimi",
                            Kategori = "Tasarim",
                            Kod = "tema_yonetimi",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 13,
                            Ad = "Proje Yonetimi",
                            Kategori = "Is",
                            Kod = "proje_yonetimi",
                            SistemModuluMu = false,
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = 14,
                            Ad = "Slayt Yonetimi",
                            Kategori = "Icerik",
                            Kod = "slayt_yonetimi",
                            SistemModuluMu = false,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 15,
                            Ad = "Referanslar",
                            Kategori = "Pazarlama",
                            Kod = "referanslar",
                            SistemModuluMu = false,
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = 16,
                            Ad = "Sertifikalar",
                            Kategori = "Kurumsal",
                            Kod = "sertifikalar",
                            SistemModuluMu = false,
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = 17,
                            Ad = "SSS",
                            Kategori = "Icerik",
                            Kod = "sss",
                            SistemModuluMu = false,
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = 18,
                            Ad = "Katalog Yonetimi",
                            Kategori = "Pazarlama",
                            Kod = "katalog",
                            SistemModuluMu = false,
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = 19,
                            Ad = "Bayi Yonetimi",
                            Kategori = "Is",
                            Kod = "bayi_yonetimi",
                            SistemModuluMu = false,
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = 20,
                            Ad = "Ekip Yonetimi",
                            Kategori = "Kurumsal",
                            Kod = "ekip_yonetimi",
                            SistemModuluMu = false,
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = 21,
                            Ad = "PWA Offline",
                            Kategori = "Teknik",
                            Kod = "pwa_offline",
                            SistemModuluMu = false,
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = 22,
                            Ad = "Audit Log",
                            Kategori = "Guvenlik",
                            Kod = "audit_log",
                            SistemModuluMu = true,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 23,
                            Ad = "Lisans Yonetimi",
                            Kategori = "Sistem",
                            Kod = "lisans_yonetimi",
                            SistemModuluMu = true,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 24,
                            Ad = "Bildirimler",
                            Kategori = "Iletisim",
                            Kod = "bildirimler",
                            SistemModuluMu = false,
                            VarsayilanMi = false
                        });
                });

            modelBuilder.Entity("VizitLink3D.SuperAdmin.VeriTabani.SuperAdminKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("SuperAdminKullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Super Admin",
                            AktifMi = true,
                            KullaniciAdi = "admin",
                            OlusturulmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SifreHash = "$2a$11$dfuOoZM6ocXVAGxj2UuXru6BoKA9RdpyPtrNt4XBxWAr6Zb32DceG"
                        });
                });

            modelBuilder.Entity("VizitLink3D.SuperAdmin.VeriTabani.SuperAdminLisansKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SuperAdminLisansKayitlari");
                });

            modelBuilder.Entity("VizitLink3D.Ortak.Modeller.FirmaModulAtama", b =>
                {
                    b.HasOne("VizitLink3D.Ortak.Modeller.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VizitLink3D.Ortak.Modeller.Modul", "Modul")
                        .WithMany()
                        .HasForeignKey("ModulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Modul");
                });

            modelBuilder.Entity("VizitLink3D.Ortak.Modeller.Lisans", b =>
                {
                    b.HasOne("VizitLink3D.Ortak.Modeller.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });
#pragma warning restore 612, 618
        }
    }
}
